# -*- coding: utf-8 -*-
"""api

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1suWPLdPu3aIneO5sy9k6EIsBn-SpUQ0y
"""

from fastapi import FastAPI
import joblib
import pandas as pd

app = FastAPI()

model = joblib.load("laptop_price_model.pkl")


@app.get("/")
def home():
    return {"message": "Laptop Price AI API is working!"}


@app.post("/predict")
def predict(
    company: str,
    type_name: str,
    inches: float,
    cpu_company: str,
    cpu_type: str,
    cpu_frequency: float,
    ram: int,
    memory: str,
    gpu_company: str,
    gpu_type: str,
    opsys: str,
    weight: float
):

    laptop = pd.DataFrame([{
        "Company": company,
        "TypeName": type_name,
        "Inches": inches,
        "CPU_Company": cpu_company,
        "CPU_Type": cpu_type,
        "CPU_Frequency (GHz)": cpu_frequency,
        "RAM (GB)": ram,
        "Memory": memory,
        "GPU_Company": gpu_company,
        "GPU_Type": gpu_type,
        "OpSys": opsys,
        "Weight (kg)": weight
    }])

    prediction = model.predict(laptop)

    price_euro = float(prediction[0])
    price_egp = price_euro * 58

    return {
        "price_euro": round(price_euro, 2),
        "price_egp": round(price_egp, 2)
    }